# Generated by Django 4.2.3 on 2023-07-10 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.IntegerField(verbose_name='Год обучения')),
                ('group', models.CharField(max_length=5, verbose_name='Группа')),
                ('class_teachers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Классные руководители')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('fathers_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegramBot.grade', verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_permission_given', models.DateTimeField(auto_now=True)),
                ('when_goes_out', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegramBot.student', verbose_name='Кому разрешение выдано?')),
                ('who_gave_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал разрешение?')),
            ],
        ),
    ]
