# Generated by Django 4.2.3 on 2023-07-10 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegramBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='reason',
            field=models.CharField(default='None', max_length=2000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TGBotAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('menu_position', models.CharField(max_length=100)),
                ('time_logged_in', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
