# Generated by Django 4.2.3 on 2023-07-11 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import telegramBot.utils.random_str_generator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegramBot', '0002_permissions_reason_tgbotauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbotauth',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tgbotauth',
            name='password',
            field=models.CharField(default=telegramBot.utils.random_str_generator.gen_string, max_length=100),
        ),
        migrations.AlterField(
            model_name='tgbotauth',
            name='menu_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tgbotauth',
            name='time_logged_in',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tgbotauth',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
