# Generated by Django 4.2.3 on 2023-07-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0003_tgbotauth_authenticated_tgbotauth_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgbotauth',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
