# Generated by Django 4.2.3 on 2023-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0004_alter_tgbotauth_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoingWithWhomReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='permissions',
            name='finished_filling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tgbotauth',
            name='tg_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='reason',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
