# Generated by Django 4.2.3 on 2023-07-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0005_goingwithwhomreasons_permissions_finished_filling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=3000)),
            ],
        ),
    ]
