# Generated by Django 4.2.3 on 2023-07-12 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegramBot', '0006_reasonsapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='class_teachers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Классные руководители'),
        ),
    ]
