# Generated by Django 4.2.3 on 2023-07-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0007_alter_grade_class_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='can_go_home_in_the_end_of_the_week',
            field=models.BooleanField(default=False, verbose_name='Может уходить домой самостоятельно в конце недели?'),
        ),
        migrations.AddField(
            model_name='student',
            name='lives_in_dormitory',
            field=models.BooleanField(default=True, verbose_name='Живет в интернате?'),
        ),
    ]
