# Generated by Django 4.2.3 on 2023-07-22 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegramBot', '0009_permissions_application_by_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='application_by_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents_set', to=settings.AUTH_USER_MODEL, verbose_name='Кто написал заявление?'),
        ),
    ]
