# Generated by Django 4.2.3 on 2023-07-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0010_student_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbotauth',
            name='type_of_user',
            field=models.CharField(choices=[('P', 'PARENT'), ('T', 'TEACHER')], default='T', max_length=30),
        ),
    ]
