# Generated by Django 4.2.3 on 2023-07-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0014_alter_permissions_who_gave_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='why_not_approved',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
